spring:
  application:
    name: resume-talk

astra:
  db:
   token: ${TOKEN}
   databaseId: ${DATABASE_ID}
   region: ${REGION}
   keyspace: ${KEYSPACE}
   table: ${TABLE}
groq:
  chat:
    base-url: ${BASE_URL}
    api-key: ${API_KEY}
    model-name: ${MODEL_NAME}

